import OpenAI from 'openai';
import { config } from './config.js';
import supabase from '../lib/supabase.js';

const openai = new OpenAI({
  apiKey: process.env.OPENROUTER_API_KEY || config.openai.apiKey,
  baseURL: process.env.OPENROUTER_API_KEY
    ? (process.env.OPENROUTER_BASE_URL || 'https://openrouter.ai/api') + '/v1'
    : undefined,
  timeout: 60000,
});

/**
 * Semantic search: embed query, then find similar chunks via pgvector.
 * @param {string} query - Natural language search query
 * @param {string} agentId - Agent ID to scope the search
 * @param {number} topK - Number of results to return
 * @returns {Promise<Array>} - Matching chunks with similarity scores
 */
export async function searchProducts(query, agentId, topK = 3) {
  // Generate embedding for the query
  const response = await openai.embeddings.create({
    model: process.env.OPENROUTER_API_KEY ? 'openai/text-embedding-3-small' : 'text-embedding-3-small',
    input: query,
  });
  const embedding = response.data[0].embedding;

  // Search via RPC
  const { data, error } = await supabase.rpc('search_product_embeddings', {
    p_agent_id: agentId,
    p_embedding: embedding,
    p_top_k: topK,
  });

  if (error) throw new Error(`search_products failed: ${error.message}`);
  return data || [];
}

/**
 * Structured query: execute dynamic SQL WHERE on product_specs via RPC.
 * @param {string} sqlWhere - WHERE clause generated by Claude
 * @param {string} agentId - Agent ID to scope the query
 * @returns {Promise<Array>} - Matching product specs
 */
export async function queryProducts(sqlWhere, agentId) {
  const { data, error } = await supabase.rpc('query_product_specs', {
    p_agent_id: agentId,
    p_where_clause: sqlWhere,
  });

  if (error) throw new Error(`query_products failed: ${error.message}`);
  return data || [];
}

/**
 * Get all distinct spec field names for an agent.
 * Used to dynamically build the query_products tool description.
 * @param {string} agentId - Agent ID
 * @returns {Promise<string[]>} - Array of field names
 */
export async function getSpecFieldsForAgent(agentId) {
  const { data, error } = await supabase.rpc('get_spec_fields', {
    p_agent_id: agentId,
  });

  if (error) throw new Error(`get_spec_fields failed: ${error.message}`);
  return data || [];
}

/**
 * Execute a product tool call from Claude.
 * @param {string} toolName - 'search_products' or 'query_products'
 * @param {Object} input - Tool input from Claude
 * @param {string} agentId - Agent ID
 * @returns {Promise<string>} - JSON string result for tool_result
 */
export async function executeProductTool(toolName, input, agentId) {
  if (toolName === 'search_products') {
    const results = await searchProducts(input.query, agentId, input.top_k || 3);
    return JSON.stringify(results);
  }

  if (toolName === 'query_products') {
    const results = await queryProducts(input.sql_where, agentId);
    return JSON.stringify(results);
  }

  return JSON.stringify({ error: `Unknown tool: ${toolName}` });
}

/**
 * Build product query tools for Claude tool_use.
 * Dynamically includes spec field names in query_products description.
 * @param {string} agentId - Agent ID
 * @returns {Promise<Array>} - Array of tool definitions
 */
export async function buildProductTools(agentId) {
  const specFields = await getSpecFieldsForAgent(agentId);

  // No product data uploaded for this agent → return empty (skip tool_use mode entirely)
  if (!specFields || specFields.length === 0) {
    return [];
  }

  const tools = [
    {
      name: 'search_products',
      description: 'Semantic search over product knowledge base. Use when customers describe needs in natural language (e.g. "200 horsepower tractor", "large fuel tank"). Returns JSON array of matching product chunks with similarity scores.',
      input_schema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            description: 'Search query in natural language',
          },
          top_k: {
            type: 'number',
            description: 'Number of results, default 3',
          },
        },
        required: ['query'],
      },
      // TODO: add allowed_callers: ['code_execution_20260120'] when OpenRouter supports programmatic tool calling
    },
    {
      name: 'query_products',
      description: `Exact query on product specs database. Use when customers ask about specific parameter comparisons (e.g. "power > 150kW", "model = DF2004E"). Returns JSON array of matching products with model, brand, product_line, and specs fields.
Table: product_specs. Query the specs JSONB field.${specFields.length > 0 ? `\nAvailable specs fields: ${specFields.join(', ')}` : ''}`,
      input_schema: {
        type: 'object',
        properties: {
          sql_where: {
            type: 'string',
            description: "SQL WHERE clause for filtering, e.g. (specs->>'nominal_power_kw')::numeric > 150",
          },
        },
        required: ['sql_where'],
      },
      // TODO: add allowed_callers: ['code_execution_20260120'] when OpenRouter supports programmatic tool calling
    },
  ];

  return tools;
}
